# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master
- releases/*

jobs:
- job:
  pool:
    vmImage: 'Ubuntu-18.04'
  strategy:
    matrix:
      Python27:
        pythonVersion: '2.7'
      Python35:
        pythonVersion: '3.5'
      Python36:
        pythonVersion: '3.6'
      Python37:
        pythonVersion: '3.7'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(pythonVersion)'
    inputs:
      versionSpec: '$(pythonVersion)'

  - script: pip install tox
    displayName: 'Install Tox'

  - script: tox -e py
    displayName: 'Run Tox'